[[big-bang-approach]]
==== [pattern]#Big Bang Approach#

===== Intent

* Replace an existing system with a completely new system (on a totally different and modern platform)
* Old and new system are not operated in parallel at all (or only for a few days or weeks)
*

===== Description


===== Experiences

* Only bad ones

===== Risks

* Software as a spec: Way too often, a big bang rewrite project
  has no proper requirements engineering. "Make it do what it already does." is an often heard answer on how a feature should
  implemented. As Chad Fowler points out in his http://chadfowler.com/2006/12/28/software-as-spec.html[blog], this has two major drawbacks: 1) if you are not familiar with the
  old system you don't know what questions to ask and 2) if you are familiar you certainly don't remember every little
  corner (especially when you need to estimate effort this will go horribly wrong). +
  Therefore you need to reverse engineer the code base to write proper requirements. Since the software is in such a bad
  condition that it needs to be rewritten you can be sure that this is not an easy task.
* Your business will certainly not like the big bang rewrite, because it takes minimum one year, often two or three to
  fully rewrite a system. This means that your business won't get any new features during that time and that could be a
  thread to the business itself. Governmental agencies might be fine with this, but the rest certainly not.
  http://www.joelonsoftware.com/articles/fog0000000069.html[Ask Netscape].
* In many cases, the business is asking for new features for the old system, while the new system is under development (nobody likes waiting 1-3 years for new features, right?.
  You will then chase a moving target, which can be a long and painful journey. The old systems has certainly some dark corners and a few stakeholders want to get
  rid of them. This is what Chad Fowler calls a http://chadfowler.com/2006/12/30/the-wish-list.html[wish list].
  Now you're at a point where you have to clearly write down the requirements, because the two systems go into two different
  directions.
* The old system usually collected a lot of bad Technical Debt (that's the reason we rewrite). In the beginning of the
  rewrite everything is good, the code is clean. But because you chase a moving target and/or need to implement new
  features you are running out of time, which introduces a lot of bad Technical Debt in the new system. You replaced a
  badly implemented system with old technology with a badly implemented system using new technology.
* The organisation creates often a culture of the "tiger team": the people who get a lot of rights, because they work on the
  new system and promise a lot. Expectations grow and are hard to manage.
* The "Big Bang Day". Eventually you have to deploy the new system and migrate the data. This needs to happen big bang and
  is therefore a major risk and more difficult to implement than smaller and incremental changes.


===== Applicability


===== Consequences


===== Also Known As

===== Related Patterns

* test

===== References

* Chad Fowler wrote a blog post series on http://chadfowler.com/2006/12/27/the-big-rewrite.html[The Big Rewrite]
* Joel Spolsky on Big Bang Rewrites: http://www.joelonsoftware.com/articles/fog0000000069.html[Things You Should Never Do, Part-I]
* David Heinemeier Hansson on https://signalvnoise.com/posts/3856-the-big-rewrite-revisited[when to fully rewrite a system]

// end of list
